import pathlib

ROOT = pathlib.Path(__file__).resolve().parent

SENSOR_TYPE_UNDEFINED = 0
SENSOR_TYPE_HUMIDITY = 1
SENSOR_TYPE_BRIGHTNESS = 2

PLANT_BASIL = 1
PLANT_PEPPERMINT = 2

PIN_HUMIDITY_BASIL = 7
PIN_HUMIDITY_PEPPERMINT = 6

PIN_PUMP_BASIL = 12
PIN_PUMP_PEPPERMINT = 16

INIT_DB = {
	'plants':[
		(PLANT_BASIL, "Basil", PIN_PUMP_BASIL, PIN_HUMIDITY_BASIL, None),
		(PLANT_PEPPERMINT, "Peppermint", PIN_PUMP_PEPPERMINT, PIN_HUMIDITY_PEPPERMINT, None)
	],
	'sensors':[
		(1, SENSOR_TYPE_HUMIDITY, "LM393", PIN_HUMIDITY_BASIL),
		(2, SENSOR_TYPE_HUMIDITY, "LM393", PIN_HUMIDITY_PEPPERMINT)
	],
	'pumps':[
		(1, PIN_PUMP_BASIL,),
		(2, PIN_PUMP_PEPPERMINT,)
	]
}